name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show tool versions
        run: |
          python -V
          pip -V

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt

      - name: Lint (ruff & black)
        run: |
          ruff --version
          black --version
          ruff check .
          black --check .

      - name: Run tests (pytest)
        env:
          PYTHONPATH: .
        run: |
          pytest -q -rA
